version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: parcellabs
    networks:
      - parcellabs-network
  test-db:
    image: postgres:13
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: parcellabs
    networks:
      - parcellabs-network
networks:
  parcellabs-network:
